# We are changing base so it creates a docker image in ghcr.io
# When stochastic-committer simulates a deployment we need to
# have a docker image for all fake repos in ghcr.io

name: Push images to registry

on:
  workflow_dispatch:

jobs:
  find-repos:
    runs-on: ubuntu-latest
    outputs:
      repos: ${{ steps.find.outputs.repos }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit

      - uses: actions/checkout@v6

      - name: Find repos with no image in ghcr.io
        id: find
        env:
          GH_TOKEN: ${{ secrets.CLONE_PUSH_REPOS }}
        run: |
          REPOS="$(./bin/find_repos_with_no_image.py)"
          echo "repos=${REPOS}" >> ${GITHUB_OUTPUT}

  fix:
    needs: [find-repos]
    if: ${{ needs.find-repos.outputs.repos != '[]' }}
    strategy:
      max-parallel: 5
      matrix:
        include: ${{ fromJSON(needs.find-repos.outputs.repos) }}
    uses: kosli-demo/stochastic-committer/.github/workflows/commit-to-repo-and-run-ci.yml@main
    with:
      scope: staging
      repo_name: ${{ matrix.repo_name }}
    secrets:
      CLONE_PUSH_REPOS: ${{ secrets.CLONE_PUSH_REPOS }}
      KOSLI_API_TOKEN_STAGING: ${{ secrets.KOSLI_API_TOKEN_STAGING }}
      KOSLI_API_TOKEN_PROD: ${{ secrets.KOSLI_API_TOKEN_PROD }}

